In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
csv_df = pd.read_csv('data.csv')

csv_df.head()

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0

In [6]:
csv_df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [7]:
csv_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0    Duration  169 non-null    int64
 1   Pulse      169 non-null    int64
 2   Maxpulse   169 non-null    int64
 3   Calories   164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [16]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("data.csv")

# Show the number of missing values in each column
print("Missing values before cleaning:\n", df.isnull().sum())

# Drop rows with any missing (NaN) values
df.dropna(inplace=True)

# Show the shape and preview the cleaned dataset
print("\nShape after removing missing values:", df.shape)
print("\nFirst few rows of cleaned data:")
print(df.head())

# Optional: Save the cleaned dataset to a new file
df.to_csv("cleaned_data_missing_values.csv", index=False)

Missing values before cleaning:
  Duration    0
Pulse        0
Maxpulse     0
Calories     5
dtype: int64

Shape after removing missing values: (164, 4)

First few rows of cleaned data:
    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0

In [18]:
import pandas as pd

# Load the dataset
df = pd.read_csv('data.csv')

# Display shape before removing duplicates
print("Before removing duplicates:", df.shape)

# Remove duplicate rows
df = df.drop_duplicates()

# Display shape after removing duplicates
print("After removing duplicates:", df.shape)

# Optionally, save the cleaned dataset
df.to_csv('data_cleaned.csv', index=False)

Before removing duplicates: (169, 4)
After removing duplicates: (162, 4)

In [21]:
import pandas as pd

# Load the dataset
df = pd.read_csv('data.csv')

# Clean up column names (in case of hidden spaces)
df.columns = df.columns.str.strip()

# Remove rows with any missing values (required for comparison)
df = df.dropna()

# Define logical constraints for valid data
valid_data = (
    (df['Duration'] > 0) & (df['Duration'] <= 300) &
    (df['Pulse'] >= 40) & (df['Pulse'] <= 200) &
    (df['Maxpulse'] >= df['Pulse']) & (df['Maxpulse'] <= 220) &
    (df['Calories'] >= 10) & (df['Calories'] <= 2000)
)

# Keep only valid rows
df_cleaned = df[valid_data]

# Save the cleaned data
df_cleaned.to_csv('cleaned_wrong_data_only.csv', index=False)

# Print summary
print("✅ Wrong data removed.")
print(f"Original rows: {len(df)}")
print(f"Cleaned rows: {len(df_cleaned)}")

✅ Wrong data removed.
Original rows: 164
Cleaned rows: 162

In [22]:
import pandas as pd

# Load dataset
df = pd.read_csv('data.csv')

# Clean up column names (remove extra spaces)
df.columns = df.columns.str.strip()

# Drop unnecessary column(s) – for example: 'Maxpulse'
columns_to_drop = ['Maxpulse']
df_cleaned = df.drop(columns=columns_to_drop)

# Save to new CSV
df_cleaned.to_csv('cleaned_unnecessary_columns_removed.csv', index=False)

# Print results
print("✅ Unnecessary columns removed.")
print(f"Remaining columns: {df_cleaned.columns.tolist()}")

✅ Unnecessary columns removed.
Remaining columns: ['Duration', 'Pulse', 'Calories']

In [27]:
import pandas as pd
from io import StringIO

data = """
Duration,Date,Pulse,Maxpulse,Calories
60,2023/10/01',110,130,409.1
60,2023/10/02',117,145,479
60,2023/10/03',103,135,340.3
45,2023/10/04',109,175,282.4
45,2023/10/05',117,150,405.1
60,2023/10/06',103,125,300
60,2023/10/07',110,135,374
400,2023/10/08',114,133,NaN
60,2023/10/09',112,126,193.8
30,2023/10/10',102,147,234.8
60,2023/10/11',100,129,375.3
60,2023/10/12',109,131,345.6
60,2023/10/13',103,136,239.2
60,2023/10/15',120,NaN,240.8
60,2023/10/15',120,100,240.8
60,2023/10/16',NaN,101,243.8
60,2023/10/17',127,102,380.2
45,20231018,142,103,241.4
60,2023/10/19',151,104,NaN
60,2023/10/20',162,105,300.9
60,2023/10/21',100,106,280
60,2023/10/22',103,107,NaN
60,NaN,130,108,230.8
60,2023/10/24',134,NaN,239.7
60,2023/10/25',132,110,236.9
60,2023/10/26',135,118,278.8
60,2023/10/27',137,119,212.9
60,2023/10/28',138,121,345.9
60,2023/10/29',139,122,345.2
60,NaN,92,125,380.5
60,2023/10/31',94,126,NaN
"""

# Load the dataset directly from the string
df = pd.read_csv(StringIO(data))

# Now you can run part 1
print("Missing values before cleaning:\n", df.isnull().sum())

df_cleaned = df.dropna(subset=['Duration', 'Pulse', 'Maxpulse', 'Calories', 'Date'])

print("\nMissing values after cleaning:\n", df_cleaned.isnull().sum())
print("\nCleaned dataset (Part 1):\n", df_cleaned)

Missing values before cleaning:
 Duration    0
Date        2
Pulse       1
Maxpulse    2
Calories    4
dtype: int64

Missing values after cleaning:
 Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

Cleaned dataset (Part 1):
     Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
14        60  2023/10/15'  120.0     100.0     240.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2

In [28]:
import pandas as pd
from io import StringIO

data = """
Duration,Date,Pulse,Maxpulse,Calories
60,2023/10/01',110,130,409.1
60,2023/10/02',117,145,479
60,2023/10/03',103,135,340.3
45,2023/10/04',109,175,282.4
45,2023/10/05',117,150,405.1
60,2023/10/06',103,125,300
60,2023/10/07',110,135,374
400,2023/10/08',114,133,NaN
60,2023/10/09',112,126,193.8
30,2023/10/10',102,147,234.8
60,2023/10/11',100,129,375.3
60,2023/10/12',109,131,345.6
60,2023/10/13',103,136,239.2
60,2023/10/15',120,NaN,240.8
60,2023/10/15',120,100,240.8
60,2023/10/16',NaN,101,243.8
60,2023/10/17',127,102,380.2
45,20231018,142,103,241.4
60,2023/10/19',151,104,NaN
60,2023/10/20',162,105,300.9
60,2023/10/21',100,106,280
60,2023/10/22',103,107,NaN
60,NaN,130,108,230.8
60,2023/10/24',134,NaN,239.7
60,2023/10/25',132,110,236.9
60,2023/10/26',135,118,278.8
60,2023/10/27',137,119,212.9
60,2023/10/28',138,121,345.9
60,2023/10/29',139,122,345.2
60,NaN,92,125,380.5
60,2023/10/31',94,126,NaN
"""

# Load data
df = pd.read_csv(StringIO(data))

# Clean and standardize Date column
df['Date'] = df['Date'].astype(str).str.replace("'", "")  # Remove stray apostrophes
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')   # Convert to datetime, invalid ones become NaT

print("Fixed Date formats:\n", df['Date'])
print("\nRows with invalid dates:\n", df[df['Date'].isnull()])

Fixed Date formats:
 0    2023-10-01
1    2023-10-02
2    2023-10-03
3    2023-10-04
4    2023-10-05
5    2023-10-06
6    2023-10-07
7    2023-10-08
8    2023-10-09
9    2023-10-10
10   2023-10-11
11   2023-10-12
12   2023-10-13
13   2023-10-15
14   2023-10-15
15   2023-10-16
16   2023-10-17
17          NaT
18   2023-10-19
19   2023-10-20
20   2023-10-21
21   2023-10-22
22          NaT
23   2023-10-24
24   2023-10-25
25   2023-10-26
26   2023-10-27
27   2023-10-28
28   2023-10-29
29          NaT
30   2023-10-31
Name: Date, dtype: datetime64[ns]

Rows with invalid dates:
     Duration Date  Pulse  Maxpulse  Calories
17        45  NaT  142.0     103.0     241.4
22        60  NaT  130.0     108.0     230.8
29        60  NaT   92.0     125.0     380.5

In [29]:
import pandas as pd
from io import StringIO

# Same raw data used from previous step
data = """
Duration,Date,Pulse,Maxpulse,Calories
60,2023/10/01',110,130,409.1
60,2023/10/02',117,145,479
60,2023/10/03',103,135,340.3
45,2023/10/04',109,175,282.4
45,2023/10/05',117,150,405.1
60,2023/10/06',103,125,300
60,2023/10/07',110,135,374
400,2023/10/08',114,133,NaN
60,2023/10/09',112,126,193.8
30,2023/10/10',102,147,234.8
60,2023/10/11',100,129,375.3
60,2023/10/12',109,131,345.6
60,2023/10/13',103,136,239.2
60,2023/10/15',120,NaN,240.8
60,2023/10/15',120,100,240.8
60,2023/10/16',NaN,101,243.8
60,2023/10/17',127,102,380.2
45,20231018,142,103,241.4
60,2023/10/19',151,104,NaN
60,2023/10/20',162,105,300.9
60,2023/10/21',100,106,280
60,2023/10/22',103,107,NaN
60,NaN,130,108,230.8
60,2023/10/24',134,NaN,239.7
60,2023/10/25',132,110,236.9
60,2023/10/26',135,118,278.8
60,2023/10/27',137,119,212.9
60,2023/10/28',138,121,345.9
60,2023/10/29',139,122,345.2
60,NaN,92,125,380.5
60,2023/10/31',94,126,NaN
"""

# Load into DataFrame
df = pd.read_csv(StringIO(data))

# Show number of duplicates before removal
print("Duplicate rows before:\n", df[df.duplicated()])

# Remove duplicates
df_cleaned = df.drop_duplicates()

# Show number of rows after removing duplicates
print("\nNumber of rows after removing duplicates:", len(df_cleaned))

Duplicate rows before:
 Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

Number of rows after removing duplicates: 31

In [30]:
import pandas as pd
from io import StringIO

data = """
Duration,Date,Pulse,Maxpulse,Calories
60,2023/10/01',110,130,409.1
60,2023/10/02',117,145,479
60,2023/10/03',103,135,340.3
45,2023/10/04',109,175,282.4
45,2023/10/05',117,150,405.1
60,2023/10/06',103,125,300
60,2023/10/07',110,135,374
400,2023/10/08',114,133,NaN
60,2023/10/09',112,126,193.8
30,2023/10/10',102,147,234.8
60,2023/10/11',100,129,375.3
60,2023/10/12',109,131,345.6
60,2023/10/13',103,136,239.2
60,2023/10/15',120,NaN,240.8
60,2023/10/15',120,100,240.8
60,2023/10/16',NaN,101,243.8
60,2023/10/17',127,102,380.2
45,20231018,142,103,241.4
60,2023/10/19',151,104,NaN
60,2023/10/20',162,105,300.9
60,2023/10/21',100,106,280
60,2023/10/22',103,107,NaN
60,NaN,130,108,230.8
60,2023/10/24',134,NaN,239.7
60,2023/10/25',132,110,236.9
60,2023/10/26',135,118,278.8
60,2023/10/27',137,119,212.9
60,2023/10/28',138,121,345.9
60,2023/10/29',139,122,345.2
60,NaN,92,125,380.5
60,2023/10/31',94,126,NaN
"""

df = pd.read_csv(StringIO(data))

# Define reasonable limits for Duration, Pulse, Maxpulse, Calories
duration_limit = 300   # max 300 minutes exercise
pulse_min, pulse_max = 50, 220  # reasonable heart rates
maxpulse_min, maxpulse_max = 50, 250
calories_min, calories_max = 0, 2000  # plausible calories burnt

# Filter out wrong Duration data
df = df[(df['Duration'] > 0) & (df['Duration'] <= duration_limit)]

# Filter Pulse and Maxpulse to reasonable ranges (replace outliers with NaN)
df.loc[~df['Pulse'].between(pulse_min, pulse_max), 'Pulse'] = pd.NA
df.loc[~df['Maxpulse'].between(maxpulse_min, maxpulse_max), 'Maxpulse'] = pd.NA

# Replace Calories outside plausible range with NaN
df.loc[~df['Calories'].between(calories_min, calories_max), 'Calories'] = pd.NA

# Show cleaned data sample
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [33]:
import pandas as pd

# Load your data (adjust the path/filename as needed)
df = pd.read_csv('mine.csv')

# Display columns before dropping
print("Columns before dropping:", df.columns.tolist())

# Drop the 'Maxpulse' column (replace with any column(s) you want to remove)
df_cleaned = df.drop(columns=['Maxpulse'])

# Display columns after dropping
print("Columns after dropping:", df_cleaned.columns.tolist())

# Optionally, save cleaned data to a new CSV file
df_cleaned.to_csv('cleaned_data.csv', index=False)

Columns before dropping: [' Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories']
Columns after dropping: [' Duration', 'Date', 'Pulse', 'Calories']

In [45]:
import pandas as pd
from io import StringIO

# Sample data (replace StringIO(data) with your CSV file path in real use)
data = """
Order ID,Customer Name,Order Date,Product,Quantity,Unit Price,Total Revenue
1001,John Doe,01/01/2024,Widget A,10,25,250
1002,Jane Smith,01/02/2024,Widget B,5,40,200
1003,,2024/01/03',Widget A,,25,
1004,Alice Johnson,04/01/2024,Widget C,3,,210
1005,Bob Brown,2024/01/05',Widget B,10,40,400
1006,John Doe,06/01/2024,Widget A,4,25,100
1001,John Doe,01/01/2024,Widget A,10,25,250
1007,Jane Smith,07/01/2024,Widget C,-6,70,-420
"""

df = pd.read_csv(StringIO(data))

print("Missing values per column before cleaning:")
print(df.isnull().sum())


# Step 1: Fix trailing apostrophes in 'Order Date'
df['Order Date'] = df['Order Date'].str.replace("'", "", regex=False)

# Step 2: Convert 'Order Date' to datetime (invalid dates become NaT)
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

# Step 3: Fill missing 'Customer Name' with 'Unknown'
df['Customer Name'] = df['Customer Name'].fillna('Unknown')

# Step 4: Handle missing or invalid Quantity
# Replace missing or non-positive quantities with median of valid positive quantities
valid_quantity = df.loc[df['Quantity'] > 0, 'Quantity']
median_quantity = valid_quantity.median()
df.loc[(df['Quantity'].isna()) | (df['Quantity'] <= 0), 'Quantity'] = median_quantity

# Step 5: Handle missing Unit Price (fill with median)
median_unit_price = df['Unit Price'].median()
df['Unit Price'] = df['Unit Price'].fillna(median_unit_price)

# Step 6: Calculate missing or invalid Total Revenue (fill missing or negative)
invalid_revenue_mask = (df['Total Revenue'].isna()) | (df['Total Revenue'] <= 0)
df.loc[invalid_revenue_mask, 'Total Revenue'] = df.loc[invalid_revenue_mask, 'Quantity'] * df.loc[invalid_revenue_mask, 'Unit Price']

# Optional: Reset index if you want
df.reset_index(drop=True, inplace=True)



print("Data after handling missing values and basic cleaning:")
print(df)

Missing values per column before cleaning:
Order ID         0
Customer Name    1
Order Date       0
Product          0
Quantity         1
Unit Price       1
Total Revenue    1
dtype: int64
Data after handling missing values and basic cleaning:
   Order ID  Customer Name Order Date   Product  Quantity  Unit Price  \
0      1001       John Doe 2024-01-01  Widget A      10.0        25.0
1      1002     Jane Smith 2024-01-02  Widget B       5.0        40.0
2      1003        Unknown        NaT  Widget A       7.5        25.0
3      1004  Alice Johnson 2024-04-01  Widget C       3.0        25.0
4      1005      Bob Brown        NaT  Widget B      10.0        40.0
5      1006       John Doe 2024-06-01  Widget A       4.0        25.0
6      1001       John Doe 2024-01-01  Widget A      10.0        25.0
7      1007     Jane Smith 2024-07-01  Widget C       7.5        70.0

   Total Revenue
0          250.0
1          200.0
2          187.5
3          210.0
4          400.0
5          100.0
6          250.0
7          525.0

In [46]:
import pandas as pd
from io import StringIO

data = """
Order ID,Customer Name,Order Date,Product,Quantity,Unit Price,Total Revenue
1001,John Doe,01/01/2024,Widget A,10,25,250
1002,Jane Smith,01/02/2024,Widget B,5,40,200
1003,,2024/01/03',Widget A,,25,
1004,Alice Johnson,04/01/2024,Widget C,3,,210
1005,Bob Brown,2024/01/05',Widget B,10,40,400
1006,John Doe,06/01/2024,Widget A,4,25,100
1001,John Doe,01/01/2024,Widget A,10,25,250
1007,Jane Smith,07/01/2024,Widget C,-6,70,-420
"""

df = pd.read_csv(StringIO(data))

# Step 1: Remove trailing apostrophes in 'Order Date'
df['Order Date'] = df['Order Date'].str.replace("'", "", regex=False)

# Step 2: Convert 'Order Date' to datetime format (infer format if possible)
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce', dayfirst=False)

print("After standardizing 'Order Date' column:")
print(df[['Order Date']])

After standardizing 'Order Date' column:
  Order Date
0 2024-01-01
1 2024-01-02
2        NaT
3 2024-04-01
4        NaT
5 2024-06-01
6 2024-01-01
7 2024-07-01

In [1]:
import pandas as pd
from io import StringIO

# Sample data
data = """
Order ID,Customer Name,Order Date,Product,Quantity,Unit Price,Total Revenue
1001,John Doe,01/01/2024,Widget A,10,25,250
1002,Jane Smith,01/02/2024,Widget B,5,40,200
1003,,2024/01/03',Widget A,,25,
1004,Alice Johnson,04/01/2024,Widget C,3,,210
1005,Bob Brown,2024/01/05',Widget B,10,40,400
1006,John Doe,06/01/2024,Widget A,4,25,100
1001,John Doe,01/01/2024,Widget A,10,25,250
1007,Jane Smith,07/01/2024,Widget C,-6,70,-420
"""

df = pd.read_csv(StringIO(data))

# Fix Order Date issues (from Part 2)
df['Order Date'] = df['Order Date'].str.replace("'", "", regex=False)
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

# Show duplicates before removal
print("Number of duplicate rows before removal:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Show after removing duplicates
print("Number of duplicate rows after removal:", df.duplicated().sum())
print("\nData after removing duplicates:")
print(df)

Number of duplicate rows before removal: 1
Number of duplicate rows after removal: 0

Data after removing duplicates:
   Order ID  Customer Name Order Date   Product  Quantity  Unit Price  \
0      1001       John Doe 2024-01-01  Widget A      10.0        25.0
1      1002     Jane Smith 2024-01-02  Widget B       5.0        40.0
2      1003            NaN        NaT  Widget A       NaN        25.0
3      1004  Alice Johnson 2024-04-01  Widget C       3.0         NaN
4      1005      Bob Brown        NaT  Widget B      10.0        40.0
5      1006       John Doe 2024-06-01  Widget A       4.0        25.0
7      1007     Jane Smith 2024-07-01  Widget C      -6.0        70.0

   Total Revenue
0          250.0
1          200.0
2            NaN
3          210.0
4          400.0
5          100.0
7         -420.0

In [2]:
import pandas as pd
from io import StringIO

# Original data
data = """
Order ID,Customer Name,Order Date,Product,Quantity,Unit Price,Total Revenue
1001,John Doe,01/01/2024,Widget A,10,25,250
1002,Jane Smith,01/02/2024,Widget B,5,40,200
1003,,2024/01/03',Widget A,,25,
1004,Alice Johnson,04/01/2024,Widget C,3,,210
1005,Bob Brown,2024/01/05',Widget B,10,40,400
1006,John Doe,06/01/2024,Widget A,4,25,100
1001,John Doe,01/01/2024,Widget A,10,25,250
1007,Jane Smith,07/01/2024,Widget C,-6,70,-420
"""

# Load into DataFrame
df = pd.read_csv(StringIO(data))

# Fix Order Date column
df['Order Date'] = df['Order Date'].str.replace("'", "", regex=False)
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

# Fill missing values (as done in Part 1)
df['Customer Name'] = df['Customer Name'].fillna('Unknown')
df['Quantity'] = df['Quantity'].fillna(df['Quantity'][df['Quantity'] > 0].median())
df['Unit Price'] = df['Unit Price'].fillna(df['Unit Price'].median())
df['Total Revenue'] = df['Total Revenue'].fillna(df['Quantity'] * df['Unit Price'])

# Remove duplicates (as done in Part 3)
df = df.drop_duplicates()

# ---- PART 4: Fix wrong data ----

# Remove or fix rows where Quantity or Unit Price is negative or zero
df.loc[df['Quantity'] <= 0, 'Quantity'] = df['Quantity'][df['Quantity'] > 0].median()
df.loc[df['Unit Price'] <= 0, 'Unit Price'] = df['Unit Price'][df['Unit Price'] > 0].median()

# Recalculate Total Revenue for rows where it's negative or inconsistent
wrong_revenue = (df['Total Revenue'] <= 0) | (df['Total Revenue'] != df['Quantity'] * df['Unit Price'])
df.loc[wrong_revenue, 'Total Revenue'] = df['Quantity'] * df['Unit Price']

print("✅ Cleaned Data after fixing wrong values:")
print(df)

✅ Cleaned Data after fixing wrong values:
   Order ID  Customer Name Order Date   Product  Quantity  Unit Price  \
0      1001       John Doe 2024-01-01  Widget A     10.00        25.0
1      1002     Jane Smith 2024-01-02  Widget B      5.00        40.0
2      1003        Unknown        NaT  Widget A      7.50        25.0
3      1004  Alice Johnson 2024-04-01  Widget C      3.00        25.0
4      1005      Bob Brown        NaT  Widget B     10.00        40.0
5      1006       John Doe 2024-06-01  Widget A      4.00        25.0
7      1007     Jane Smith 2024-07-01  Widget C      6.25        70.0

   Total Revenue
0          250.0
1          200.0
2          187.5
3           75.0
4          400.0
5          100.0
7          437.5

In [3]:
import pandas as pd
from io import StringIO

# Sample raw data
data = """
Order ID,Customer Name,Order Date,Product,Quantity,Unit Price,Total Revenue
1001,John Doe,01/01/2024,Widget A,10,25,250
1002,Jane Smith,01/02/2024,Widget B,5,40,200
1003,,2024/01/03',Widget A,,25,
1004,Alice Johnson,04/01/2024,Widget C,3,,210
1005,Bob Brown,2024/01/05',Widget B,10,40,400
1006,John Doe,06/01/2024,Widget A,4,25,100
1001,John Doe,01/01/2024,Widget A,10,25,250
1007,Jane Smith,07/01/2024,Widget C,-6,70,-420
"""

# Load into DataFrame
df = pd.read_csv(StringIO(data))

# Step 1: Fix Order Date format
df['Order Date'] = df['Order Date'].str.replace("'", "", regex=False)
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')

# Step 2: Handle missing values
df['Customer Name'] = df['Customer Name'].fillna('Unknown')
df['Quantity'] = df['Quantity'].fillna(df['Quantity'][df['Quantity'] > 0].median())
df['Unit Price'] = df['Unit Price'].fillna(df['Unit Price'].median())
df['Total Revenue'] = df['Total Revenue'].fillna(df['Quantity'] * df['Unit Price'])

# Step 3: Remove duplicate rows
df = df.drop_duplicates()

# Step 4: Fix wrong data
df.loc[df['Quantity'] <= 0, 'Quantity'] = df['Quantity'][df['Quantity'] > 0].median()
df.loc[df['Unit Price'] <= 0, 'Unit Price'] = df['Unit Price'][df['Unit Price'] > 0].median()
wrong_revenue = (df['Total Revenue'] <= 0) | (df['Total Revenue'] != df['Quantity'] * df['Unit Price'])
df.loc[wrong_revenue, 'Total Revenue'] = df['Quantity'] * df['Unit Price']

# ✅ Step 5: Remove unnecessary columns (just keep what's relevant)
expected_columns = ['Order ID', 'Customer Name', 'Order Date', 'Product', 'Quantity', 'Unit Price', 'Total Revenue']
df = df[expected_columns]  # Ensures only relevant columns are kept

print("✅ Final Cleaned Dataset:")
print(df)

✅ Final Cleaned Dataset:
   Order ID  Customer Name Order Date   Product  Quantity  Unit Price  \
0      1001       John Doe 2024-01-01  Widget A     10.00        25.0
1      1002     Jane Smith 2024-01-02  Widget B      5.00        40.0
2      1003        Unknown        NaT  Widget A      7.50        25.0
3      1004  Alice Johnson 2024-04-01  Widget C      3.00        25.0
4      1005      Bob Brown        NaT  Widget B     10.00        40.0
5      1006       John Doe 2024-06-01  Widget A      4.00        25.0
7      1007     Jane Smith 2024-07-01  Widget C      6.25        70.0

   Total Revenue
0          250.0
1          200.0
2          187.5
3           75.0
4          400.0
5          100.0
7          437.5